---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-aggregator-service-deployment
  labels:
    app: nagp-aggregator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nagp-aggregator-service
  template:
    metadata:
      labels:
        app: nagp-aggregator-service
    spec:
      containers:
        - name: nagp-aggregator-service
          image: prateek91sharma/nagp-aggregator-service:latest
          env:
            - name: opentracing.jaeger.udp-sender.host
              value: jaeger-agent 
            - name: opentracing.jaeger.udp-sender.port
              value: "6831"    
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nagp-aggregator-service
spec:
  selector:
    app: nagp-aggregator-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: LoadBalancer  
  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ribbon-list-server-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io            
 